---
- name: Add webupd8 PPA for Java7
  apt_repository: repo=ppa:webupd8team/java
 
- name: Update apt cache
  apt: update_cache=yes
 
- name: Install Java7
  # Installer is interactive so force all answers to yes.
  # http://askubuntu.com/a/190674/67778
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true |
         debconf-set-selections && 
         echo debconf shared/accepted-oracle-license-v1-1 seen true | 
         debconf-set-selections &&
         apt-get -y install oracle-java7-installer

- name: Install Maven
  apt: pkg=maven

