---
- name: Install Yeoman
  npm: name=yo
       global=yes

- name: Install Angular-Dropwizard Generator
  npm: name=generator-angular-dropwizard
       global=yes

- name: Copy application Expect script
  copy: src=generate_app.exp dest=/tmp/generate_app.exp
  sudo: false

- name: Copy entity Expect script
  copy: src=generate_entity.exp dest=/tmp/generate_entity.exp
  sudo: false

- name: Generate application
  shell: mkdir /tmp/testapp; cd /tmp/testapp; /tmp/generate_app.exp
  sudo: false
  when: generate_testapp|bool

- name: Generate entity
  shell: cd /tmp/testapp; /tmp/generate_entity.exp
  sudo: false
  when: generate_testapp|bool

- name: Build application
  shell: cd /tmp/testapp; mvn compile 
  sudo: false
  when: generate_testapp|bool

- name: Run application
  shell: cd /tmp/testapp; nohup mvn exec:exec -pl yourapp-service >app.log 2>&1 &
  sudo: false
  when: generate_testapp|bool
  async: 10
  poll: 0

